### ISSUE TITLE
Persistent storage / export

### ISSUE THREAD

**Issue by Daviey** [awehook/blink-mind#1]
Hi,

How do you persistently store and/or export the chart for longevity?

Thanks

**Comment by awehook** [comment]
The plugin plugin-json-serializer has been added to the framework, you can use it to persistently store and/or export the chart. You can view the [online demo](https://awehook.github.io/blink-mind/?path=/story/serializer-demo--json-serializer), The source code is [here](https://github.com/awehook/blink-mind/blob/master/stories/serialize-demo/index.stories.jsx)
