### ISSUE TITLE
hello，冒昧打扰

### ISSUE THREAD

**Issue by zwhu** [awehook/blink-mind#2]
在掘金看到你的文章，跟我们现在的技术栈挺匹配的，不知道是否考虑杭州阿里的工作机会？

因为没有找到联系方式，所以在此留言，如有困扰，请关闭 issue 即可

**Comment by awehook** [comment]
可以加我QQ: 776524978, 或者通过邮箱awehook@163.com, 私聊哈

**Comment by zwhu** [comment]
已加 qq
